# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InspectionMode.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InspectionModeWindow(object):
    def setupUi(self, InspectionModeWindow):
        InspectionModeWindow.setObjectName("InspectionModeWindow")
        InspectionModeWindow.resize(628, 535)
        self.centralWidget = QtWidgets.QWidget(InspectionModeWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 581, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 350, 581, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.good = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.good.setAlignment(QtCore.Qt.AlignCenter)
        self.good.setObjectName("good")
        self.horizontalLayout.addWidget(self.good)
        self.goodNum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.goodNum.setObjectName("goodNum")
        self.horizontalLayout.addWidget(self.goodNum)
        self.liefeng = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.liefeng.setAlignment(QtCore.Qt.AlignCenter)
        self.liefeng.setObjectName("liefeng")
        self.horizontalLayout.addWidget(self.liefeng)
        self.liefengNum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.liefengNum.setObjectName("liefengNum")
        self.horizontalLayout.addWidget(self.liefengNum)
        self.quejiao = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.quejiao.setAlignment(QtCore.Qt.AlignCenter)
        self.quejiao.setObjectName("quejiao")
        self.horizontalLayout.addWidget(self.quejiao)
        self.quejiaoNum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.quejiaoNum.setObjectName("quejiaoNum")
        self.horizontalLayout.addWidget(self.quejiaoNum)
        self.duanshan = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.duanshan.setAlignment(QtCore.Qt.AlignCenter)
        self.duanshan.setObjectName("duanshan")
        self.horizontalLayout.addWidget(self.duanshan)
        self.duanshanNum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.duanshanNum.setObjectName("duanshanNum")
        self.horizontalLayout.addWidget(self.duanshanNum)
        self.xuhan = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.xuhan.setAlignment(QtCore.Qt.AlignCenter)
        self.xuhan.setObjectName("xuhan")
        self.horizontalLayout.addWidget(self.xuhan)
        self.xuhanNum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.xuhanNum.setObjectName("xuhanNum")
        self.horizontalLayout.addWidget(self.xuhanNum)
        self.duanlu = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.duanlu.setAlignment(QtCore.Qt.AlignCenter)
        self.duanlu.setObjectName("duanlu")
        self.horizontalLayout.addWidget(self.duanlu)
        self.duanluNum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.duanluNum.setObjectName("duanluNum")
        self.horizontalLayout.addWidget(self.duanluNum)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hundang = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.hundang.setAlignment(QtCore.Qt.AlignCenter)
        self.hundang.setObjectName("hundang")
        self.horizontalLayout_2.addWidget(self.hundang)
        self.hundangNum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.hundangNum.setObjectName("hundangNum")
        self.horizontalLayout_2.addWidget(self.hundangNum)
        self.heixinheiban = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.heixinheiban.setAlignment(QtCore.Qt.AlignCenter)
        self.heixinheiban.setObjectName("heixinheiban")
        self.horizontalLayout_2.addWidget(self.heixinheiban)
        self.heixinheibanNum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.heixinheibanNum.setObjectName("heixinheibanNum")
        self.horizontalLayout_2.addWidget(self.heixinheibanNum)
        self.tongxinyuan = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tongxinyuan.setAlignment(QtCore.Qt.AlignCenter)
        self.tongxinyuan.setObjectName("tongxinyuan")
        self.horizontalLayout_2.addWidget(self.tongxinyuan)
        self.tongxinyuanNum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tongxinyuanNum.setObjectName("tongxinyuanNum")
        self.horizontalLayout_2.addWidget(self.tongxinyuanNum)
        self.heibian = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.heibian.setAlignment(QtCore.Qt.AlignCenter)
        self.heibian.setObjectName("heibian")
        self.horizontalLayout_2.addWidget(self.heibian)
        self.heibianNum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.heibianNum.setObjectName("heibianNum")
        self.horizontalLayout_2.addWidget(self.heibianNum)
        self.heijiao = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.heijiao.setAlignment(QtCore.Qt.AlignCenter)
        self.heijiao.setObjectName("heijiao")
        self.horizontalLayout_2.addWidget(self.heijiao)
        self.heijiaoNum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.heijiaoNum.setObjectName("heijiaoNum")
        self.horizontalLayout_2.addWidget(self.heijiaoNum)
        self.liangban = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.liangban.setAlignment(QtCore.Qt.AlignCenter)
        self.liangban.setObjectName("liangban")
        self.horizontalLayout_2.addWidget(self.liangban)
        self.liangbanNum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.liangbanNum.setObjectName("liangbanNum")
        self.horizontalLayout_2.addWidget(self.liangbanNum)
        self.huahen = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.huahen.setAlignment(QtCore.Qt.AlignCenter)
        self.huahen.setObjectName("huahen")
        self.horizontalLayout_2.addWidget(self.huahen)
        self.huahenNum = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.huahenNum.setObjectName("huahenNum")
        self.horizontalLayout_2.addWidget(self.huahenNum)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 470, 581, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scanButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.scanButton.setObjectName("scanButton")
        self.horizontalLayout_3.addWidget(self.scanButton)
        self.startScanButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startScanButton.setObjectName("startScanButton")
        self.horizontalLayout_3.addWidget(self.startScanButton)
        self.stopScanButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopScanButton.setObjectName("stopScanButton")
        self.horizontalLayout_3.addWidget(self.stopScanButton)
        self.historyButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.historyButton.setObjectName("historyButton")
        self.horizontalLayout_3.addWidget(self.historyButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 500, 581, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fileName = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.fileName.setObjectName("fileName")
        self.horizontalLayout_4.addWidget(self.fileName)
        self.scanDirectoryLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.scanDirectoryLabel.setObjectName("scanDirectoryLabel")
        self.horizontalLayout_4.addWidget(self.scanDirectoryLabel)
        InspectionModeWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(InspectionModeWindow)
        QtCore.QMetaObject.connectSlotsByName(InspectionModeWindow)

    def retranslateUi(self, InspectionModeWindow):
        _translate = QtCore.QCoreApplication.translate
        InspectionModeWindow.setWindowTitle(_translate("InspectionModeWindow", "太阳能电池板检测系统-生产模式"))
        self.good.setText(_translate("InspectionModeWindow", "良品 :"))
        self.goodNum.setText(_translate("InspectionModeWindow", "0"))
        self.liefeng.setText(_translate("InspectionModeWindow", "裂缝 :"))
        self.liefengNum.setText(_translate("InspectionModeWindow", "0"))
        self.quejiao.setText(_translate("InspectionModeWindow", "缺角 :"))
        self.quejiaoNum.setText(_translate("InspectionModeWindow", "0"))
        self.duanshan.setText(_translate("InspectionModeWindow", "断栅 :"))
        self.duanshanNum.setText(_translate("InspectionModeWindow", "0"))
        self.xuhan.setText(_translate("InspectionModeWindow", "虚焊 :"))
        self.xuhanNum.setText(_translate("InspectionModeWindow", "0"))
        self.duanlu.setText(_translate("InspectionModeWindow", "断路 :"))
        self.duanluNum.setText(_translate("InspectionModeWindow", "0"))
        self.hundang.setText(_translate("InspectionModeWindow", "混档 :"))
        self.hundangNum.setText(_translate("InspectionModeWindow", "0"))
        self.heixinheiban.setText(_translate("InspectionModeWindow", "黑心黑斑 :"))
        self.heixinheibanNum.setText(_translate("InspectionModeWindow", "0"))
        self.tongxinyuan.setText(_translate("InspectionModeWindow", "同心圆 :"))
        self.tongxinyuanNum.setText(_translate("InspectionModeWindow", "0"))
        self.heibian.setText(_translate("InspectionModeWindow", "黑边 :"))
        self.heibianNum.setText(_translate("InspectionModeWindow", "0"))
        self.heijiao.setText(_translate("InspectionModeWindow", "黑角 :"))
        self.heijiaoNum.setText(_translate("InspectionModeWindow", "0"))
        self.liangban.setText(_translate("InspectionModeWindow", "亮斑 :"))
        self.liangbanNum.setText(_translate("InspectionModeWindow", "0"))
        self.huahen.setText(_translate("InspectionModeWindow", "划痕 :"))
        self.huahenNum.setText(_translate("InspectionModeWindow", "0"))
        self.scanButton.setText(_translate("InspectionModeWindow", "打开扫描文件夹"))
        self.startScanButton.setText(_translate("InspectionModeWindow", "开始检测"))
        self.stopScanButton.setText(_translate("InspectionModeWindow", "停止检测"))
        self.historyButton.setText(_translate("InspectionModeWindow", "历史数据"))
        self.fileName.setText(_translate("InspectionModeWindow", "文件名:"))
        self.scanDirectoryLabel.setText(_translate("InspectionModeWindow", "扫描文件夹:"))

